-- ----------------------------------------------------------
-- MDB Tools - A library for reading MS Access database files
-- Copyright (C) 2000-2011 Brian Bruns and others.
-- Files in libmdb are licensed under LGPL and the utilities under
-- the GPL, see COPYING.LIB and COPYING files respectively.
-- Check out http://mdbtools.sourceforge.net
-- ----------------------------------------------------------

-- That file uses encoding UTF-8

CREATE TABLE [AccessDeniedLogs]
 (
	[AccessDeniedDateTime]			DateTime NOT NULL, 
	[StationID]			Long Integer NOT NULL, 
	[AccessDeniedType]			Text (1) NOT NULL, 
	[AttemptedAccessCode]			Long Integer, 
	[EmployeeID]			Long Integer, 
	[AttemptedFeatureName]			Text (254) NOT NULL, 
	[AutoID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [BadCheckFiles]
 (
	[BadCheckID]			Long Integer, 
	[CustomerID]			Long Integer NOT NULL, 
	[FirstName]			Text (15) NOT NULL, 
	[LastName]			Text (15) NOT NULL, 
	[Address]			Text (30) NOT NULL, 
	[ZipCode]			Text (10) NOT NULL, 
	[DriverLicenseNumber]			Text (20), 
	[CheckIssueDate]			DateTime NOT NULL, 
	[ABANumber]			Text (5), 
	[CheckingAcctNumber]			Text (20) NOT NULL, 
	[CheckNumber]			Long Integer NOT NULL, 
	[CheckAmount]			Single NOT NULL, 
	[RefOrderNumber]			Long Integer, 
	[BadCheckReasonID]			Long Integer NOT NULL, 
	[BadCheckPenaltyID]			Long Integer NOT NULL, 
	[BadCheckPenaltyAmount]			Single NOT NULL, 
	[BadCheckNotes]			Text (254), 
	[BankID]			Long Integer NOT NULL, 
	[CollectionStatus]			Text (1) NOT NULL, 
	[AlertCode]			Text (1) NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [BadCheckPenalties]
 (
	[BadCheckPenaltyID]			Long Integer, 
	[BadCheckPenaltyText]			Text (20) NOT NULL, 
	[BadCheckPenaltyAmount]			Single NOT NULL, 
	[BadCheckPenaltyInActive]			Boolean NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [BankFiles]
 (
	[BankID]			Long Integer, 
	[BankName]			Text (20) NOT NULL, 
	[VerifyFundsByPhone]			Boolean NOT NULL, 
	[BankFileHidden]			Boolean NOT NULL, 
	[EditTimestamp]			DateTime, 
	[PhoneNumber]			Text (15) NOT NULL, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [BarTabPreAuth]
 (
	[AutoID]			Long Integer NOT NULL, 
	[OrderID]			Long Integer NOT NULL, 
	[AcctNum]			Text (20) NOT NULL, 
	[Exp]			Text (4) NOT NULL, 
	[OrigAuthAmount]			Single NOT NULL, 
	[OrigAuthCode]			Text (20) NOT NULL, 
	[OrigRefNum]			Text (20), 
	[LimitReached]			Boolean NOT NULL, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [CallerIDLogs]
 (
	[CallDateTime]			DateTime NOT NULL, 
	[CallerName]			Text (30) NOT NULL, 
	[AutoID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[PhoneNumber]			Text (15) NOT NULL, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [CashTrays]
 (
	[CashTrayID]			Long Integer, 
	[CashTrayText]			Text (10) NOT NULL, 
	[CashTrayInActive]			Boolean NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [CCPreAuth]
 (
	[OrderID]			Long Integer NOT NULL, 
	[AcctNum]			Text (20) NOT NULL, 
	[Exp]			Text (4) NOT NULL, 
	[OrigAuthAmount]			Single NOT NULL, 
	[OrigAuthCode]			Text (20) NOT NULL, 
	[OrigRefNum]			Text (20), 
	[AutoID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[EDCTransID]			Long Integer, 
	[EDCCardLast4]			Text (10), 
	[EDCCardType]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [ChecksForDeposit]
 (
	[CheckAmount]			Single NOT NULL, 
	[DepositSlipID]			Long Integer, 
	[AutoID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [ComplimentaryAmounts]
 (
	[ComplimentaryAmountID]			Long Integer, 
	[PaymentDateTime]			DateTime NOT NULL, 
	[CashierID]			Long Integer NOT NULL, 
	[NonCashierEmployeeID]			Long Integer, 
	[OrderID]			Long Integer NOT NULL, 
	[PaymentAmount]			Single NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [CustomerCredits]
 (
	[CreditID]			Long Integer, 
	[CreditDateTime]			DateTime NOT NULL, 
	[CustomerID]			Long Integer NOT NULL, 
	[EmployeeID]			Long Integer NOT NULL, 
	[CreditReason]			Text (254) NOT NULL, 
	[CreditLimitations]			Text (254), 
	[CreditType]			Text (1) NOT NULL, 
	[CreditAmount]			Single NOT NULL, 
	[CreditStatus]			Text (1) NOT NULL, 
	[CreditVoidReason]			Text (254), 
	[CreditExpireDate]			DateTime, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [CustomerFiles]
 (
	[CustomerID]			Long Integer, 
	[CustomerName]			Text (30) NOT NULL, 
	[CustomerNotes]			Text (254), 
	[DeliveryAddress]			Text (30), 
	[CrossStreet]			Text (30), 
	[ZipCode]			Text (10), 
	[DeliveryRemarks]			Text (254), 
	[DeliveryCharge]			Single, 
	[DeliveryComp]			Single, 
	[ScanCode]			Text (254), 
	[AccountCode]			Text (10), 
	[EditTimestamp]			DateTime, 
	[PhoneNumber]			Text (15) NOT NULL, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[CompanyName]			Text (50), 
	[EmailAddress]			Text (100), 
	[VIPType]			Integer, 
	[PictureName]			Text (254), 
	[AnniversaryMonth]			Integer, 
	[BirthMonth]			Integer, 
	[CustomerSinceDate]			DateTime, 
	[TotalSpent]			Single, 
	[TotalCount]			Long Integer, 
	[AverageOrder]			Single, 
	[LastOrderDate]			DateTime, 
	[LastOrderAmount]			Single, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [CustomPrinterTypes]
 (
	[PrinterTypeID]			Long Integer, 
	[PrinterTypeName]			Text (30) NOT NULL, 
	[FontBold]			Text (30), 
	[FontNoBold]			Text (30), 
	[FontLarge]			Text (30), 
	[FontSmall]			Text (30), 
	[FontRed]			Text (30), 
	[FontNoRed]			Text (30), 
	[CashDrawerBel]			Text (30), 
	[LineFeed]			Text (30), 
	[AutoCut]			Text (30), 
	[Buzzard]			Text (30), 
	[LargeFontColumns]			Text (30), 
	[SmallFontColumns]			Text (30), 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[Drawer2Bel]			Text (254), 
	[BeginBarcode]			Text (254), 
	[EndBarcode]			Text (254), 
	[ManualAutoCut]			Boolean NOT NULL, 
	[InitializeCode]			Text (254), 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [DailyClosingRegistry]
 (
	[ClosingDate]			DateTime NOT NULL, 
	[CCBatch]			Single NOT NULL, 
	[AmexBatch]			Single NOT NULL, 
	[Transfered]			Single NOT NULL, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [DailyInvRecap]
 (
	[AutoID]			Long Integer NOT NULL, 
	[RecapDate]			DateTime NOT NULL, 
	[InventoryItemID]			Long Integer NOT NULL, 
	[EndingQty]			Single, 
	[EndingValue]			Single, 
	[ReceivedQty]			Single, 
	[ReceivedValue]			Single, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [DBCompatibility]
 (
	[DBCompatibility]			Text (10) NOT NULL, 
	[AutoID]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer
);

CREATE TABLE [DepositSlips]
 (
	[DepositSlipID]			Long Integer, 
	[DepositDateTime]			DateTime NOT NULL, 
	[CurrencyAmount]			Single NOT NULL, 
	[CoinsAmount]			Single NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [DineInTables]
 (
	[DineInTableID]			Long Integer, 
	[DineInTableText]			Text (6) NOT NULL, 
	[TableGroupID]			Long Integer NOT NULL, 
	[DisplayIndex]			Long Integer NOT NULL, 
	[DineInTableInActive]			Boolean NOT NULL, 
	[MaxGuests]			Long Integer, 
	[Hibachi]			Boolean NOT NULL, 
	[HBStyle]			Text (1), 
	[HibachiBridgeTo]			Text (10), 
	[HibachiBridgeSeats]			Integer, 
	[HBLeftSeats]			Integer, 
	[HBTopSeats]			Integer, 
	[HBBottomSeats]			Integer, 
	[HBRightSeats]			Integer, 
	[Smoking]			Boolean NOT NULL, 
	[Window]			Boolean NOT NULL, 
	[Booth]			Boolean NOT NULL, 
	[Privacy]			Boolean NOT NULL, 
	[PictureName]			Text (254), 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [Discounts]
 (
	[DiscountID]			Long Integer, 
	[DiscountText]			Text (20) NOT NULL, 
	[DiscountDescription]			Text (254), 
	[DiscountedAmountTaxable]			Boolean NOT NULL, 
	[DiscountExpireDate]			DateTime, 
	[DiscountInActive]			Boolean NOT NULL, 
	[DiscountAmount]			Single NOT NULL, 
	[DiscountBasis]			Text (1) NOT NULL, 
	[DiscountAllowedMinTicket]			Single, 
	[Barcode]			Text (20), 
	[DiscountMenuItemID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[DiscountItemNotAvail]			Boolean NOT NULL, 
	[DiscountOrderNotAvail]			Boolean NOT NULL, 
	[DiscountSecurityLevel]			Integer, 
	[BaseMMGCode]			Text (50), 
	[BaseMMGQty]			Integer, 
	[OfferMMGCode]			Text (50), 
	[OfferMMGQty]			Integer, 
	[BOGO]			Boolean NOT NULL, 
	[BXF]			Boolean NOT NULL, 
	[ExcludeBarItems]			Boolean NOT NULL, 
	[VIPUseOnly]			Boolean NOT NULL, 
	[DineInNotAvail]			Boolean NOT NULL, 
	[BarNotAvail]			Boolean NOT NULL, 
	[TakeOutNotAvail]			Boolean NOT NULL, 
	[DriveThruNotAvail]			Boolean NOT NULL, 
	[DeliveryNotAvail]			Boolean NOT NULL, 
	[EffectiveDate]			DateTime, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [Email]
 (
	[ToEmployeeID]			Long Integer NOT NULL, 
	[EmailDateTime]			DateTime NOT NULL, 
	[Message]			Text (254), 
	[FromEmployeeID]			Long Integer NOT NULL, 
	[EmailID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [EmployeeFiles]
 (
	[EmployeeID]			Long Integer, 
	[FirstName]			Text (15) NOT NULL, 
	[MiddleInitial]			Text (1), 
	[LastName]			Text (15) NOT NULL, 
	[SocialSecurityNumber]			Text (20), 
	[MailingAddress]			Text (30), 
	[MailingZipCode]			Text (10), 
	[DateHired]			DateTime, 
	[DateReleased]			DateTime, 
	[EmployeeInActive]			Boolean NOT NULL, 
	[JobTitleID]			Long Integer NOT NULL, 
	[SecurityLevel]			Text (1) NOT NULL, 
	[AccessCode]			Text (8), 
	[TipsReceived]			Boolean NOT NULL, 
	[PayBasis]			Text (1) NOT NULL, 
	[PayRate]			Single NOT NULL, 
	[ScanCode]			Text (254), 
	[DriverLicenseNumber]			Text (20), 
	[DriverLicenseExpires]			DateTime, 
	[CarInsurancePolicyCarrier]			Text (30), 
	[CarInsurancePolicyNumber]			Text (20), 
	[CarInsurancePolicyExpires]			DateTime, 
	[CarInsurancePolicyNotes]			Text (254), 
	[PrefUserInterfaceLocale]			Text (2) NOT NULL, 
	[EmployeeNotes]			Text (254), 
	[OrderEntryUseSecLang]			Boolean NOT NULL, 
	[EmployeeIsDriver]			Boolean NOT NULL, 
	[DefaultOEMenuGroupID]			Long Integer, 
	[UseStaffBank]			Boolean NOT NULL, 
	[ScheduleNotEnforced]			Boolean NOT NULL, 
	[UseHostess]			Boolean NOT NULL, 
	[IsAServer]			Boolean NOT NULL, 
	[NoCashierOut]			Boolean NOT NULL, 
	[EditTimestamp]			DateTime, 
	[PhoneNumber]			Text (15), 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[DineInNotAvail]			Boolean NOT NULL, 
	[BarNotAvail]			Boolean NOT NULL, 
	[TakeOutNotAvail]			Boolean NOT NULL, 
	[DriveThruNotAvail]			Boolean NOT NULL, 
	[DeliveryNotAvail]			Boolean NOT NULL, 
	[UseEmail]			Boolean NOT NULL, 
	[EmailAddress]			Text (100), 
	[PictureName]			Text (254), 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[HolidayPayScale]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [EmployeePayrollHistory]
 (
	[PayrollID]			Long Integer, 
	[EmployeeID]			Long Integer NOT NULL, 
	[PayPeriodBeginDate]			DateTime NOT NULL, 
	[PayPeriodEndDate]			DateTime NOT NULL, 
	[PayBasis]			Text (1) NOT NULL, 
	[PayRate]			Single NOT NULL, 
	[OTPayRate]			Single, 
	[AdditionalPay]			Single, 
	[RegularHours]			Single, 
	[OverTimeHours]			Single, 
	[TotalTips]			Single, 
	[TotalWageAdvance]			Single, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[DoubleTimeHours]			Single, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [EmployeeSchedules]
 (
	[ScheduleID]			Long Integer, 
	[EmployeeID]			Long Integer NOT NULL, 
	[WeekDay]			Text (1) NOT NULL, 
	[ClockInTime]			DateTime NOT NULL, 
	[ClockOutTime]			DateTime NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[Break1BeginTime]			DateTime, 
	[Break1EndTime]			DateTime, 
	[Break1Compensated]			Boolean NOT NULL, 
	[Break2BeginTime]			DateTime, 
	[Break2EndTime]			DateTime, 
	[Break2Compensated]			Boolean NOT NULL, 
	[Break3BeginTime]			DateTime, 
	[Break3EndTime]			DateTime, 
	[Break3Compensated]			Boolean NOT NULL, 
	[Break4BeginTime]			DateTime, 
	[Break4EndTime]			DateTime, 
	[Break4Compensated]			Boolean NOT NULL, 
	[Break5BeginTime]			DateTime, 
	[Break5EndTime]			DateTime, 
	[Break5Compensated]			Boolean NOT NULL, 
	[TotalRegularMinutes]			Long Integer, 
	[TotalDailyOverTimeMinutes]			Long Integer, 
	[TotalWeeklyOverTimeMinutes]			Long Integer, 
	[TotalDoubleTimeMinutes]			Long Integer, 
	[TotalWorkMinutes]			Long Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [FacturaTable]
 (
	[AutoID]			Long Integer NOT NULL, 
	[OrderID]			Long Integer NOT NULL, 
	[FacturaNumber]			Long Integer NOT NULL, 
	[TotalDue]			Single NOT NULL, 
	[Status]			Boolean NOT NULL, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [FreqDinerFiles]
 (
	[CustomerID]			Long Integer NOT NULL, 
	[FirstName]			Text (15) NOT NULL, 
	[LastName]			Text (15) NOT NULL, 
	[MailingAddress]			Text (30), 
	[MailingZipCode]			Text (10), 
	[ScanCode]			Text (254), 
	[AutoID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[EmailAddress]			Text (50), 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [FreqDinerTrackings]
 (
	[CustomerID]			Long Integer NOT NULL, 
	[EmployeeID]			Long Integer NOT NULL, 
	[TrackingDateTime]			DateTime NOT NULL, 
	[OrderID]			Long Integer NOT NULL, 
	[RewardCreditID]			Long Integer, 
	[AutoID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [GeneralSettings]
 (
	[RestaurantName]			Text (30) NOT NULL, 
	[SiteNumber]			Long Integer, 
	[PremiseAddress]			Text (30) NOT NULL, 
	[PremiseZipCode]			Text (10) NOT NULL, 
	[MailingAddress]			Text (30) NOT NULL, 
	[MailingZipCode]			Text (10) NOT NULL, 
	[DefaultDeliveryCharge]			Single, 
	[DefaultDeliveryComp]			Single, 
	[DineInService]			Boolean NOT NULL, 
	[TakeOutService]			Boolean NOT NULL, 
	[DriveThruService]			Boolean NOT NULL, 
	[DeliveryService]			Boolean NOT NULL, 
	[QuickService]			Boolean NOT NULL, 
	[AcceptCheck]			Boolean NOT NULL, 
	[AcceptVisa]			Boolean NOT NULL, 
	[AcceptMastercard]			Boolean NOT NULL, 
	[AcceptAmericanExpress]			Boolean NOT NULL, 
	[AcceptNovusCards]			Boolean NOT NULL, 
	[AcceptATM]			Boolean NOT NULL, 
	[AcceptCarteBlanche]			Boolean NOT NULL, 
	[AcceptDinersInternational]			Boolean NOT NULL, 
	[AcceptOnAccount]			Boolean NOT NULL, 
	[SalesTaxRate]			Single NOT NULL, 
	[ConfirmExitProgram]			Boolean NOT NULL, 
	[AutoPrintOrder]			Boolean NOT NULL, 
	[AutoPrintReceipt]			Boolean NOT NULL, 
	[FreqDinerMinTicket]			Single, 
	[FreqDinerStartTime]			DateTime, 
	[FreqDinerStopTime]			DateTime, 
	[KitchenUseSecLang]			Boolean NOT NULL, 
	[BarUseSecLang]			Boolean NOT NULL, 
	[PayPeriod]			Text (1) NOT NULL, 
	[HourlyOverTimePercent]			Single NOT NULL, 
	[OnAccountDueDay]			Text (2), 
	[GuestReceiptMessage]			Text (254), 
	[TakeOutOnHoldForNewCust]			Boolean NOT NULL, 
	[KitchenPrefLocaleID]			Text (2) NOT NULL, 
	[BarPrefLocaleID]			Text (2) NOT NULL, 
	[AutoGratuityPercent]			Long Integer, 
	[AutoPrintGratuityClaimReceipt]			Boolean NOT NULL, 
	[LastDayOfWorkWeek]			Text (1) NOT NULL, 
	[PrintCreditCardTipLine]			Boolean NOT NULL, 
	[PictureName]			Text (254), 
	[OverTimeHoursAfter]			Single NOT NULL, 
	[OverTimeHourBasis]			Text (1) NOT NULL, 
	[CallerIDComPort]			Text (1), 
	[GSTRate]			Single, 
	[PerformCheckScan]			Boolean NOT NULL, 
	[GuestCheckPrefLocaleID]			Text (2), 
	[GuestCheckUseSecLang]			Boolean NOT NULL, 
	[OrderEntrySingleItem]			Boolean NOT NULL, 
	[ServerBanking]			Boolean NOT NULL, 
	[HideGreenIndicatorOnSavedOrder]			Boolean NOT NULL, 
	[HideVoidedItemFromPrintedGuestCheck]			Boolean NOT NULL, 
	[RecallOrderByTable]			Boolean NOT NULL, 
	[ForceClearInUseTable]			Boolean NOT NULL, 
	[HideModifierFromGuestCheckWithoutCost]			Boolean NOT NULL, 
	[HideModifierCostFromGuestCheck]			Boolean NOT NULL, 
	[TrackGuestNumber]			Boolean NOT NULL, 
	[LunchStartTime]			DateTime NOT NULL, 
	[DinnerStartTime]			DateTime NOT NULL, 
	[PerformMenuExplosion]			Boolean NOT NULL, 
	[IntegratedCreditCardProcessing]			Boolean NOT NULL, 
	[MinimumRecipeProfitMarginPercent]			Long Integer NOT NULL, 
	[HideOrderHoldUntilTimeFromPrintedGuestCheck]			Boolean NOT NULL, 
	[HideItemHoldUntilTimeFromPrintedGuestCheck]			Boolean NOT NULL, 
	[HideExpiredHoldTime]			Boolean NOT NULL, 
	[EDCTimeOut]			Long Integer, 
	[EDCLastValidYear]			Text (2), 
	[EDCActiveChargePath]			Text (254), 
	[EDCUserName]			Text (8), 
	[EDCReceiptCopies]			Long Integer, 
	[HideVoidedMenuItemFromScreen]			Boolean NOT NULL, 
	[FreqDinerRewardAfterCount]			Long Integer, 
	[FreqDinerRewardAfterAmount]			Single, 
	[FreqDinerRewardCreditAmount]			Single, 
	[AutomaticFreqDinerRewardCreation]			Boolean NOT NULL, 
	[DailySpecialsMessage]			Text (254), 
	[DisplayDailySpecials]			Boolean NOT NULL, 
	[DesignatedDriveThruStations]			Boolean NOT NULL, 
	[DisableDriveThruTiming]			Boolean NOT NULL, 
	[AutoID]			Long Integer, 
	[ModBuilderType1]			Text (20), 
	[PhoneNumber]			Text (15) NOT NULL, 
	[DefaultAreaCode]			Text (5) NOT NULL, 
	[ModBuilderType2]			Text (20), 
	[ModBuilderType3]			Text (20), 
	[ModBuilderType4]			Text (20), 
	[ModBuilderType5]			Text (20), 
	[ModBuilderType6]			Text (20), 
	[ModBuilderType7]			Text (20), 
	[ModBuilderType8]			Text (20), 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[LastPollTimestamp]			DateTime, 
	[LastSynchVer]			DateTime, 
	[ExtendedSettings]			Memo/Hyperlink (255), 
	[HostessSettings]			Memo/Hyperlink (255), 
	[PCCSettings]			Memo/Hyperlink (255), 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [GiftCertificates]
 (
	[GiftCertificateID]			Long Integer, 
	[IssuedDateTime]			DateTime NOT NULL, 
	[InternalSequenceNumber]			Text (10), 
	[EmployeeID]			Long Integer NOT NULL, 
	[IssuedToName]			Text (30) NOT NULL, 
	[PresentedByName]			Text (30) NOT NULL, 
	[IssuedAmount]			Single NOT NULL, 
	[ExpirationDate]			DateTime, 
	[GiftCertificateStatus]			Text (1) NOT NULL, 
	[GCVoidReason]			Text (254), 
	[ScanCode]			Text (254), 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[GCSAcctNo]			Text (30), 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [GiftCertificateUsages]
 (
	[GiftCertificateID]			Long Integer NOT NULL, 
	[OrderID]			Long Integer NOT NULL, 
	[GiftCertificateAmountUsed]			Single NOT NULL, 
	[UsageDateTime]			DateTime NOT NULL, 
	[CashierID]			Long Integer NOT NULL, 
	[NonCashierEmployeeID]			Long Integer, 
	[EmployeeComp]			Single NOT NULL, 
	[AutoID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[EDCTransID]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [InventoryGroups]
 (
	[InventoryGroupID]			Long Integer, 
	[InventoryGroupText]			Text (30) NOT NULL, 
	[InventoryGroupInActive]			Boolean NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [InventoryLocations]
 (
	[InventoryLocationID]			Long Integer, 
	[InventoryLocationText]			Text (30) NOT NULL, 
	[InventoryLocationInActive]			Boolean NOT NULL, 
	[LocationDisplaySeqNumber]			Long Integer NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [InventoryPhysicalCounts]
 (
	[InventoryPhysicalCountID]			Long Integer, 
	[PhysicalCountDateTime]			DateTime NOT NULL, 
	[InventoryID]			Long Integer NOT NULL, 
	[StartQty]			Single NOT NULL, 
	[StartValue]			Single NOT NULL, 
	[StartUnitCost]			Single NOT NULL, 
	[EndQty]			Single NOT NULL, 
	[EndValue]			Single NOT NULL, 
	[EndUnitCost]			Single NOT NULL, 
	[UsedQty]			Single NOT NULL, 
	[UsedValue]			Single NOT NULL, 
	[UsedUnitCost]			Single NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [InventoryUOMs]
 (
	[UOMID]			Long Integer NOT NULL, 
	[UOMName]			Text (30) NOT NULL, 
	[RecipeUnits]			Long Integer NOT NULL, 
	[UOMInActive]			Boolean NOT NULL, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [InventoryVendors]
 (
	[InventoryVendorID]			Long Integer, 
	[InventoryVendorText]			Text (30) NOT NULL, 
	[InventoryVendorInActive]			Boolean NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [JobTitles]
 (
	[JobTitleID]			Long Integer, 
	[JobTitleText]			Text (30) NOT NULL, 
	[DefaultTipsReceived]			Boolean NOT NULL, 
	[DefaultSecurityLevel]			Text (1) NOT NULL, 
	[DefaultPayBasis]			Text (1) NOT NULL, 
	[DefaultPayRate]			Single NOT NULL, 
	[JobTitleInActive]			Boolean NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [ManagerCashOuts]
 (
	[AutoID]			Long Integer NOT NULL, 
	[CashOutDateTime]			DateTime NOT NULL, 
	[CashierID]			Long Integer NOT NULL, 
	[ManagerID]			Long Integer NOT NULL, 
	[CashOutAmount]			Single NOT NULL, 
	[CashOutVoided]			Boolean NOT NULL, 
	[VoidReason]			Text (254), 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [MenuExplosion]
 (
	[OrderTransactionID]			Long Integer NOT NULL, 
	[InventoryItemID]			Long Integer NOT NULL, 
	[TotalUnitsUsed]			Single NOT NULL, 
	[AutoID]			Long Integer, 
	[MenuIngredientUnitCost]			Single NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [MenuGroups]
 (
	[MenuGroupID]			Long Integer, 
	[MenuGroupText]			Text (15) NOT NULL, 
	[DisplayIndex]			Long Integer NOT NULL, 
	[MenuGroupInActive]			Boolean NOT NULL, 
	[SecLangMenuGroupText]			Text (16), 
	[AvailStartTime]			DateTime, 
	[AvailStopTime]			DateTime, 
	[PictureName]			Text (254), 
	[ShowCaption]			Boolean NOT NULL, 
	[ButtonColor]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[DineInNotAvail]			Boolean NOT NULL, 
	[BarNotAvail]			Boolean NOT NULL, 
	[TakeOutNotAvail]			Boolean NOT NULL, 
	[DriveThruNotAvail]			Boolean NOT NULL, 
	[DeliveryNotAvail]			Boolean NOT NULL, 
	[DefaultGroupDineIn]			Boolean NOT NULL, 
	[DefaultGroupBar]			Boolean NOT NULL, 
	[DefaultGroupToGo]			Boolean NOT NULL, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [MenuGroupSchedule]
 (
	[AutoID]			Long Integer NOT NULL, 
	[MenuGroupID]			Long Integer NOT NULL, 
	[WeekDay]			Integer NOT NULL, 
	[AvailStartTime]			DateTime NOT NULL, 
	[AvailStopTime]			DateTime NOT NULL, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [MenuItemIngredients]
 (
	[MenuItemID]			Long Integer NOT NULL, 
	[InventoryItemID]			Long Integer NOT NULL, 
	[UnitsUsed]			Single NOT NULL, 
	[AutoID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [MenuItemPrices]
 (
	[MenuItemPriceID]			Long Integer, 
	[MenuItemID]			Long Integer NOT NULL, 
	[WeekDay]			Text (1) NOT NULL, 
	[PriceStartTime]			DateTime NOT NULL, 
	[PriceStopTime]			DateTime NOT NULL, 
	[UnitPrice]			Single NOT NULL, 
	[AutoPriceText]			Text (6) NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [MenuItems]
 (
	[MenuItemID]			Long Integer, 
	[MenuItemText]			Text (22) NOT NULL, 
	[MenuCategoryID]			Long Integer NOT NULL, 
	[MenuGroupID]			Long Integer NOT NULL, 
	[DisplayIndex]			Long Integer NOT NULL, 
	[DefaultUnitPrice]			Single NOT NULL, 
	[MenuItemDescription]			Text (254), 
	[MenuItemNotification]			Text (1) NOT NULL, 
	[MenuItemInActive]			Boolean NOT NULL, 
	[MenuItemInStock]			Boolean NOT NULL, 
	[MenuItemTaxable]			Boolean NOT NULL, 
	[MenuItemDiscountable]			Boolean NOT NULL, 
	[MenuItemType]			Text (1) NOT NULL, 
	[MenuItemPopUpHeaderID]			Long Integer, 
	[MenuItemPopUpChoiceText]			Text (22), 
	[HasModifierPopUps]			Boolean NOT NULL, 
	[SecLangMenuItemText]			Text (22), 
	[SecLangPopUpChoiceText]			Text (22), 
	[PictureName]			Text (254), 
	[ShowCaption]			Boolean NOT NULL, 
	[GSTApplied]			Boolean NOT NULL, 
	[Pizza]			Boolean NOT NULL, 
	[Bar]			Boolean NOT NULL, 
	[DefaultModifierType]			Text (1), 
	[ButtonColor]			Long Integer, 
	[Barcode]			Text (20), 
	[GasPump]			Text (3), 
	[FoodStampsPayable]			Boolean NOT NULL, 
	[LiquorTaxApplied]			Boolean NOT NULL, 
	[ItemDelCharge]			Single, 
	[ItemDelComp]			Single, 
	[JumpMenuGroupID]			Long Integer, 
	[LargePictureName]			Text (254), 
	[DineInPrice]			Single, 
	[BarTabPrice]			Single, 
	[TakeOutPrice]			Single, 
	[DriveThruPrice]			Single, 
	[DeliveryPrice]			Single, 
	[OrderByWeight]			Boolean NOT NULL, 
	[PrintPizzaLabel]			Boolean NOT NULL, 
	[KitchenSortNumber]			Long Integer, 
	[ModBuilderTemplateID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[QtyCountDown]			Single, 
	[MenuItemCost]			Single, 
	[PizzaSize]			Integer, 
	[PizzaToppingThreshold]			Integer, 
	[PizzaToppingFreeInThreshold]			Boolean NOT NULL, 
	[ScreenName]			Text (50), 
	[ScreenAltName]			Text (50), 
	[ReceiptName]			Text (50), 
	[ReceiptAltName]			Text (50), 
	[ChitName]			Text (50), 
	[ChitAltName]			Text (50), 
	[PrintToKitchen1]			Boolean NOT NULL, 
	[PrintToKitchen2]			Boolean NOT NULL, 
	[PrintToKitchen3]			Boolean NOT NULL, 
	[PrintToKitchen4]			Boolean NOT NULL, 
	[PrintToKitchen5]			Boolean NOT NULL, 
	[PrintToKitchen6]			Boolean NOT NULL, 
	[PrintToBar]			Boolean NOT NULL, 
	[PrintItemDetailOnReceipt]			Boolean NOT NULL, 
	[PrintItemDetailToKitchen]			Boolean NOT NULL, 
	[PrintItemDetailToBar]			Boolean NOT NULL, 
	[PrintableItemDetails]			Text (254), 
	[ScriptDetails]			Text (254), 
	[MixMatchCode]			Text (50), 
	[DoNotPrintOnReceipt]			Boolean NOT NULL, 
	[OpenPriceItem]			Boolean NOT NULL, 
	[OpenPriceAskDescription]			Boolean NOT NULL, 
	[OpenPriceSecurityLevel]			Integer, 
	[LCPLU]			Long Integer, 
	[AllowPostEntryAdjustQty]			Boolean NOT NULL, 
	[MinProfitPercent]			Single, 
	[DisallowDiscountIfAutoPriced]			Boolean NOT NULL, 
	[MinimumPrice]			Single, 
	[MaximumPrice]			Single, 
	[HideFromPrepForecast]			Boolean NOT NULL, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[LotMaxQty]			Long Integer, 
	[LotChild]			Boolean NOT NULL, 
	[ShowQtyInTBS]			Boolean NOT NULL, 
	[MaxQtyInputPerItem]			Long Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [MenuModifiers]
 (
	[MenuModifierID]			Long Integer, 
	[MenuModifierText]			Text (24) NOT NULL, 
	[AdditionalCost]			Single, 
	[MenuModifierInActive]			Boolean NOT NULL, 
	[SecLangModifierText]			Text (24), 
	[PictureName]			Text (254), 
	[ShowCaption]			Boolean NOT NULL, 
	[PizzaCrust]			Boolean NOT NULL, 
	[PizzaTopping]			Boolean NOT NULL, 
	[BarMixer]			Boolean NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[PizzaSize]			Integer, 
	[ScreenName]			Text (50), 
	[ScreenAltName]			Text (50), 
	[ReceiptName]			Text (50), 
	[ReceiptAltName]			Text (50), 
	[ChitName]			Text (50), 
	[ChitAltName]			Text (50), 
	[PizzaSauce]			Boolean NOT NULL, 
	[LCPLU]			Long Integer, 
	[ActionType]			Integer, 
	[ActionBaseModifierID]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [ModBuilderDetails]
 (
	[ModBuilderDetailID]			Long Integer NOT NULL, 
	[ModBuilderTemplateID]			Long Integer NOT NULL, 
	[ModBuilderType]			Integer NOT NULL, 
	[MenuModifierID]			Long Integer NOT NULL, 
	[AdditionalCost]			Single, 
	[NoTypeModifierID]			Long Integer, 
	[NoTypeCost]			Single, 
	[AddTypeModifierID]			Long Integer, 
	[AddTypeCost]			Single, 
	[ExtraTypeModifierID]			Long Integer, 
	[ExtraTypeCost]			Single, 
	[LightTypeModifierID]			Long Integer, 
	[LightTypeCost]			Single, 
	[ExchgTypeModifierID]			Long Integer, 
	[ExchgTypeCost]			Single, 
	[DoubleTypeModifierID]			Long Integer, 
	[DoubleTypeCost]			Single, 
	[TripleTypeModifierID]			Long Integer, 
	[TripleTypeCost]			Single, 
	[HalfTypeModifierID]			Long Integer, 
	[HalfTypeCost]			Single, 
	[DisplayIndex]			Integer NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[ExcludeBaseModifier]			Boolean NOT NULL, 
	[SelectedAsDefault]			Boolean NOT NULL, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [ModBuilderTemplates]
 (
	[ModBuilderTemplateID]			Long Integer NOT NULL, 
	[ModBuilderTemplateText]			Text (30) NOT NULL, 
	[UseModBuilderType1]			Boolean NOT NULL, 
	[UseModBuilderType2]			Boolean NOT NULL, 
	[UseModBuilderType3]			Boolean NOT NULL, 
	[UseModBuilderType4]			Boolean NOT NULL, 
	[UseModBuilderType5]			Boolean NOT NULL, 
	[UseModBuilderType6]			Boolean NOT NULL, 
	[UseModBuilderType7]			Boolean NOT NULL, 
	[UseModBuilderType8]			Boolean NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[Type1Name]			Text (30), 
	[Type2Name]			Text (30), 
	[Type3Name]			Text (30), 
	[Type4Name]			Text (30), 
	[Type5Name]			Text (30), 
	[Type6Name]			Text (30), 
	[Type7Name]			Text (30), 
	[Type8Name]			Text (30), 
	[Type1DefaultAction]			Integer, 
	[Type2DefaultAction]			Integer, 
	[Type3DefaultAction]			Integer, 
	[Type4DefaultAction]			Integer, 
	[Type5DefaultAction]			Integer, 
	[Type6DefaultAction]			Integer, 
	[Type7DefaultAction]			Integer, 
	[Type8DefaultAction]			Integer, 
	[Type1MinSelect]			Integer, 
	[Type1MaxSelect]			Integer, 
	[Type2MinSelect]			Integer, 
	[Type2MaxSelect]			Integer, 
	[Type3MinSelect]			Integer, 
	[Type3MaxSelect]			Integer, 
	[Type4MinSelect]			Integer, 
	[Type4MaxSelect]			Integer, 
	[Type5MinSelect]			Integer, 
	[Type5MaxSelect]			Integer, 
	[Type6MinSelect]			Integer, 
	[Type6MaxSelect]			Integer, 
	[Type7MinSelect]			Integer, 
	[Type7MaxSelect]			Integer, 
	[Type8MinSelect]			Integer, 
	[Type8MaxSelect]			Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [NewFactura]
 (
	[AutoID]			Long Integer NOT NULL, 
	[FacturaNumber]			Long Integer NOT NULL, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [NoSaleLogs]
 (
	[NoSaleDateTime]			DateTime NOT NULL, 
	[CashierID]			Long Integer NOT NULL, 
	[NonCashierEmployeeID]			Long Integer, 
	[NoSaleReason]			Text (254) NOT NULL, 
	[AutoID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [OnAccountCharges]
 (
	[OrderChargeID]			Long Integer, 
	[ChargeDateTime]			DateTime NOT NULL, 
	[CashierID]			Long Integer NOT NULL, 
	[NonCashierEmployeeID]			Long Integer, 
	[CustomerID]			Long Integer NOT NULL, 
	[OrderID]			Long Integer NOT NULL, 
	[AmountCharged]			Single NOT NULL, 
	[OrderChargePaymentID]			Long Integer, 
	[EmployeeComp]			Single NOT NULL, 
	[ChargeDueDate]			DateTime NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[EDCTransID]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [OnAccountPayments]
 (
	[OrderChargePaymentID]			Long Integer, 
	[PaymentDateTime]			DateTime NOT NULL, 
	[CashierID]			Long Integer NOT NULL, 
	[NonCashierEmployeeID]			Long Integer, 
	[AmountPaid]			Single NOT NULL, 
	[PaymentMethod]			Text (1) NOT NULL, 
	[AmountTendered]			Single NOT NULL, 
	[OrderChargeID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[EDCTransID]			Long Integer, 
	[EDCCardLast4]			Text (10), 
	[EDCCardType]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [OrderHeaders]
 (
	[OrderID]			Long Integer, 
	[OrderDateTime]			DateTime NOT NULL, 
	[EmployeeID]			Long Integer NOT NULL, 
	[StationID]			Long Integer NOT NULL, 
	[OrderType]			Text (1) NOT NULL, 
	[DineInTableID]			Long Integer, 
	[CustomerID]			Long Integer, 
	[DeliveryCharge]			Single, 
	[DeliveryComp]			Single, 
	[DriverEmployeeID]			Long Integer, 
	[DriverDepartureTime]			DateTime, 
	[DriverArrivalTime]			DateTime, 
	[OnHoldUntilTime]			DateTime, 
	[SalesTaxRate]			Single NOT NULL, 
	[DiscountID]			Long Integer, 
	[DiscountAmount]			Single, 
	[DiscountBasis]			Text (1), 
	[DiscountTaxable]			Boolean NOT NULL, 
	[OrderStatus]			Text (1) NOT NULL, 
	[AmountDue]			Single NOT NULL, 
	[Kitchen1AlreadyPrinted]			Boolean NOT NULL, 
	[Kitchen2AlreadyPrinted]			Boolean NOT NULL, 
	[Kitchen3AlreadyPrinted]			Boolean NOT NULL, 
	[BarAlreadyPrinted]			Boolean NOT NULL, 
	[PackagerAlreadyPrinted]			Boolean NOT NULL, 
	[SurchargeID]			Long Integer, 
	[SurchargeAmount]			Single, 
	[SurchargeBasis]			Text (1), 
	[CashDiscountAmount]			Single, 
	[CashDiscountApprovalEmpID]			Long Integer, 
	[SubTotal]			Single NOT NULL, 
	[GratuityPercent]			Long Integer, 
	[CashGratuity]			Single, 
	[CreditID]			Long Integer, 
	[CreditAmountUsed]			Single, 
	[DiscountAmountUsed]			Single, 
	[SurchargeAmountUsed]			Single, 
	[SalesTaxAmountUsed]			Single NOT NULL, 
	[DriveThruComplete]			DateTime, 
	[GSTRate]			Single, 
	[GSTAmountUsed]			Single, 
	[BarTabName]			Text (30), 
	[ServerBankID]			Long Integer, 
	[TableReady]			Boolean NOT NULL, 
	[GuestNumber]			Long Integer, 
	[SpecificCustomerName]			Text (30), 
	[GuestCheckPrinted]			Boolean NOT NULL, 
	[ServerBankType]			Text (1), 
	[ServerBankAmount]			Single, 
	[Kitchen4AlreadyPrinted]			Boolean NOT NULL, 
	[Kitchen5AlreadyPrinted]			Boolean NOT NULL, 
	[Kitchen6AlreadyPrinted]			Boolean NOT NULL, 
	[LiquorTaxRate]			Single, 
	[LiquorTaxAmount]			Single, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[FacturaNumber]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[BarTabPreAuth]			Boolean NOT NULL, 
	[ParentOrderID]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [OrderPayments]
 (
	[OrderPaymentID]			Long Integer, 
	[PaymentDateTime]			DateTime NOT NULL, 
	[CashierID]			Long Integer NOT NULL, 
	[NonCashierEmployeeID]			Long Integer, 
	[OrderID]			Long Integer NOT NULL, 
	[PaymentMethod]			Text (1) NOT NULL, 
	[AmountTendered]			Single NOT NULL, 
	[AmountPaid]			Single NOT NULL, 
	[EditTimestamp]			DateTime, 
	[EmployeeComp]			Single NOT NULL, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[EDCTransID]			Long Integer, 
	[EDCCardLast4]			Text (10), 
	[EDCCardType]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [OrderRefunds]
 (
	[RefundDateTime]			DateTime NOT NULL, 
	[OrderID]			Long Integer, 
	[CashierID]			Long Integer NOT NULL, 
	[NonCashierEmployeeID]			Long Integer, 
	[AmountRefunded]			Single NOT NULL, 
	[RefundMethod]			Text (1) NOT NULL, 
	[AutoID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RefundReason]			Text (254) NOT NULL, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[EDCTransID]			Long Integer, 
	[EDCCardLast4]			Text (10), 
	[EDCCardType]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [OrderTransactions]
 (
	[OrderTransactionID]			Long Integer, 
	[OrderID]			Long Integer NOT NULL, 
	[MenuItemID]			Long Integer NOT NULL, 
	[MenuItemAutoPriceText]			Text (6), 
	[MenuItemUnitPrice]			Single NOT NULL, 
	[Quantity]			Single NOT NULL, 
	[ExtendedPrice]			Single NOT NULL, 
	[DiscountID]			Long Integer, 
	[DiscountAmount]			Single, 
	[DiscountBasis]			Text (1), 
	[DiscountTaxable]			Boolean NOT NULL, 
	[TransactionStatus]			Text (1) NOT NULL, 
	[NotificationStatus]			Text (1) NOT NULL, 
	[Mod1ID]			Long Integer, 
	[Mod1Cost]			Single, 
	[Mod2ID]			Long Integer, 
	[Mod2Cost]			Single, 
	[Mod3ID]			Long Integer, 
	[Mod3Cost]			Single, 
	[Mod4ID]			Long Integer, 
	[Mod4Cost]			Single, 
	[Mod5ID]			Long Integer, 
	[Mod5Cost]			Single, 
	[Mod6ID]			Long Integer, 
	[Mod6Cost]			Single, 
	[Mod7ID]			Long Integer, 
	[Mod7Cost]			Single, 
	[Mod8ID]			Long Integer, 
	[Mod8Cost]			Single, 
	[Mod9ID]			Long Integer, 
	[Mod9Cost]			Single, 
	[Mod10ID]			Long Integer, 
	[Mod10Cost]			Single, 
	[Mod11ID]			Long Integer, 
	[Mod11Cost]			Single, 
	[Mod12ID]			Long Integer, 
	[Mod12Cost]			Single, 
	[Mod13ID]			Long Integer, 
	[Mod13Cost]			Single, 
	[Mod14ID]			Long Integer, 
	[Mod14Cost]			Single, 
	[Mod15ID]			Long Integer, 
	[Mod15Cost]			Single, 
	[Mod16ID]			Long Integer, 
	[Mod16Cost]			Single, 
	[Mod17ID]			Long Integer, 
	[Mod17Cost]			Single, 
	[Mod18ID]			Long Integer, 
	[Mod18Cost]			Single, 
	[Mod19ID]			Long Integer, 
	[Mod19Cost]			Single, 
	[Mod20ID]			Long Integer, 
	[Mod20Cost]			Single, 
	[DiscountAmountUsed]			Single, 
	[SeatNumber]			Long Integer, 
	[OnHoldUntilTime]			DateTime, 
	[GSTTaxable]			Boolean NOT NULL, 
	[ShortNote]			Text (40), 
	[FoodStampsPayable]			Boolean NOT NULL, 
	[LiquorTaxApplied]			Boolean NOT NULL, 
	[PizzaLabelPrinted]			Boolean NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[Kitchen1Printed]			Boolean NOT NULL, 
	[Kitchen2Printed]			Boolean NOT NULL, 
	[Kitchen3Printed]			Boolean NOT NULL, 
	[Kitchen4Printed]			Boolean NOT NULL, 
	[Kitchen5Printed]			Boolean NOT NULL, 
	[Kitchen6Printed]			Boolean NOT NULL, 
	[BarPrinted]			Boolean NOT NULL, 
	[CourseNumber]			Long Integer, 
	[ItemFired]			Boolean NOT NULL, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [OrderVoidLogs]
 (
	[OrderID]			Long Integer NOT NULL, 
	[OrderTransactionID]			Long Integer, 
	[EmployeeID]			Long Integer NOT NULL, 
	[VoidReason]			Text (254) NOT NULL, 
	[VoidDateTime]			DateTime NOT NULL, 
	[VoidForItemReduction]			Boolean NOT NULL, 
	[VoidAmount]			Single NOT NULL, 
	[AutoID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [OtherPayments]
 (
	[OtherPaymentID]			Long Integer, 
	[PaymentDateTime]			DateTime NOT NULL, 
	[CashierID]			Long Integer NOT NULL, 
	[NonCashierEmployeeID]			Long Integer NOT NULL, 
	[BadCheckID]			Long Integer, 
	[GiftCertificateID]			Long Integer, 
	[AmountPaid]			Single NOT NULL, 
	[PaymentMethod]			Text (1) NOT NULL, 
	[AmountTendered]			Single NOT NULL, 
	[BadCheckPaymentSource]			Text (1), 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[EDCTransID]			Long Integer, 
	[EDCCardLast4]			Text (10), 
	[EDCCardType]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [PayOuts]
 (
	[PayOutID]			Long Integer, 
	[PayOutDateTime]			DateTime NOT NULL, 
	[CashierID]			Long Integer NOT NULL, 
	[NonCashierEmployeeID]			Long Integer, 
	[PayOutToName]			Text (30) NOT NULL, 
	[PayOutDescription]			Text (254) NOT NULL, 
	[PayOutAmount]			Single NOT NULL, 
	[WageAdvanceEmployeeID]			Long Integer, 
	[PayOutVoided]			Boolean NOT NULL, 
	[VoidReason]			Text (254), 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [PDAClients]
 (
	[ComputerName]			Text (20) NOT NULL, 
	[License]			Text (26), 
	[CCode]			Text (4), 
	[LoginDateTime]			DateTime, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer
);

CREATE TABLE [PrankCallFiles]
 (
	[PrankCallID]			Long Integer, 
	[RecordedDateTime]			DateTime NOT NULL, 
	[RecordedEmployeeID]			Long Integer NOT NULL, 
	[CustomerID]			Long Integer NOT NULL, 
	[RefOrderNumber]			Long Integer, 
	[PrankDetails]			Text (254) NOT NULL, 
	[AmountLossed]			Boolean NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [PurchaseOrderDetails]
 (
	[PurchaseOrderDetailID]			Long Integer, 
	[PurchaseOrderID]			Long Integer NOT NULL, 
	[InventoryItemID]			Long Integer NOT NULL, 
	[Quantity]			Single NOT NULL, 
	[UnitCost]			Single, 
	[BulkQtyName]			Text (30) NOT NULL, 
	[UnitsPerQty]			Single NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [PurchaseOrders]
 (
	[PurchaseOrderID]			Long Integer, 
	[OrderDateTime]			DateTime NOT NULL, 
	[InventoryVendorID]			Long Integer NOT NULL, 
	[Received]			Boolean NOT NULL, 
	[InternalNumber]			Text (10), 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [RegisterCashiers]
 (
	[CashierID]			Long Integer, 
	[EmployeeID]			Long Integer NOT NULL, 
	[CashTrayID]			Long Integer NOT NULL, 
	[StationID]			Long Integer NOT NULL, 
	[SignInDateTime]			DateTime NOT NULL, 
	[RegisterStartAmount]			Single NOT NULL, 
	[SignOutDateTime]			DateTime, 
	[RegisterEndAmount]			Single, 
	[DiscrepancyAmount]			Single, 
	[DiscrepancyNotes]			Text (254), 
	[ManagerEmployeeID]			Long Integer, 
	[TotalCash]			Single, 
	[TotalChecks]			Single, 
	[TotalCharges]			Single, 
	[ZReportID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[TotalRoomCharges]			Single, 
	[TotalHouseCharges]			Single, 
	[CashDrawerNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [Reservations]
 (
	[AutoID]			Long Integer NOT NULL, 
	[PartyName]			Text (30) NOT NULL, 
	[Occasion]			Text (10), 
	[Adults]			Integer NOT NULL, 
	[Children]			Integer, 
	[HighChairs]			Integer, 
	[WheelChairs]			Integer, 
	[ReserveDateTime]			DateTime NOT NULL, 
	[Smoking]			Boolean NOT NULL, 
	[Window]			Boolean NOT NULL, 
	[Booth]			Boolean NOT NULL, 
	[Privacy]			Boolean NOT NULL, 
	[Notes]			Text (254), 
	[TableIDAssigned]			Long Integer, 
	[CreditCardNumber]			Text (30), 
	[PartyCheckInDateTime]			DateTime, 
	[ReservationCancelled]			Boolean NOT NULL, 
	[WhoPays]			Text (30), 
	[EditTimestamp]			DateTime, 
	[Phone]			Text (15), 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[bWaitingList]			Boolean NOT NULL, 
	[PagerNumber]			Text (30), 
	[CustomerID]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [RowChanges]
 (
	[AutoID]			Long Integer NOT NULL, 
	[LogDateTime]			DateTime NOT NULL, 
	[DBTableName]			Text (100), 
	[SourceRowGUID]			Text (50), 
	[SourceRowDeleteAction]			Boolean NOT NULL, 
	[DirectSQL]			Memo/Hyperlink (255), 
	[Mirrored]			Boolean NOT NULL, 
	[HQSynched]			Boolean NOT NULL
);

CREATE TABLE [RowDeleteLog]
 (
	[AutoID]			Long Integer NOT NULL, 
	[TargetTableCode]			Long Integer NOT NULL, 
	[TargetGlobalID]			Text (30) NOT NULL, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[EventDateTime]			DateTime, 
	[TargetTableName]			Text (50), 
	[TargetHQRowID]			Text (50), 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [ServerDrawers]
 (
	[StationID]			Long Integer NOT NULL, 
	[ServerID]			Long Integer NOT NULL, 
	[DrawerNo]			Long Integer NOT NULL, 
	[AutoID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [StationSettings]
 (
	[StationID]			Long Integer, 
	[ComputerName]			Text (20) NOT NULL, 
	[ReceiptPrinterPort]			Text (254) NOT NULL, 
	[ReceiptPrinterType]			Long Integer NOT NULL, 
	[CashDrawerAttached]			Boolean NOT NULL, 
	[KitchenPrinter1Title]			Text (20) NOT NULL, 
	[KitchenPrinter1Port]			Text (254) NOT NULL, 
	[KitchenPrinter1Type]			Long Integer NOT NULL, 
	[KitchenPrinter1Name]			Text (254) NOT NULL, 
	[KitchenPrinter2Title]			Text (20), 
	[KitchenPrinter2Port]			Text (254), 
	[KitchenPrinter2Type]			Long Integer, 
	[KitchenPrinter2Name]			Text (254), 
	[KitchenPrinter3Title]			Text (20), 
	[KitchenPrinter3Port]			Text (254), 
	[KitchenPrinter3Type]			Long Integer, 
	[KitchenPrinter3Name]			Text (254), 
	[BarPrinterPort]			Text (254), 
	[BarPrinterType]			Long Integer, 
	[ReportPrinterPort]			Text (254), 
	[DedicatedToCashier]			Boolean NOT NULL, 
	[UserInterfaceLocale]			Text (2) NOT NULL, 
	[ReceiptPrinterName]			Text (254) NOT NULL, 
	[BarPrinterName]			Text (254), 
	[ReportPrinterName]			Text (254), 
	[PackagerPrinterPort]			Text (254), 
	[PackagerPrinterType]			Long Integer, 
	[PackagerPrinterName]			Text (254), 
	[FastBar]			Boolean NOT NULL, 
	[DefaultTableGroupID]			Long Integer, 
	[BarTab]			Boolean NOT NULL, 
	[OrderRecallToBrowse]			Boolean NOT NULL, 
	[OrderRecallOrderType]			Text (1), 
	[DefaultToMenuGroupsInOrderEntry]			Boolean NOT NULL, 
	[HasEDC]			Boolean NOT NULL, 
	[DriveThruStation]			Boolean NOT NULL, 
	[BarTabCaption]			Text (15), 
	[PoleDisplayCommPort]			Text (1), 
	[PoleDisplayWelcomeMessage1]			Text (20), 
	[CallerIDCommPort]			Text (1), 
	[KeepInOrderEntryAfterSent]			Boolean NOT NULL, 
	[PoleDisplayWelcomeMessage2]			Text (20), 
	[KitchenPrinter4Title]			Text (20), 
	[KitchenPrinter4Name]			Text (254), 
	[KitchenPrinter4Type]			Long Integer, 
	[KitchenPrinter5Title]			Text (20), 
	[KitchenPrinter5Name]			Text (254), 
	[KitchenPrinter5Type]			Long Integer, 
	[KitchenPrinter6Title]			Text (20), 
	[KitchenPrinter6Name]			Text (254), 
	[KitchenPrinter6Type]			Long Integer, 
	[LabelPrinterName]			Text (254), 
	[LabelPrinterType]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[RerouteBar1Title]			Text (30), 
	[RerouteBar1PrinterName]			Text (254), 
	[RerouteBar1PrinterType]			Long Integer, 
	[RerouteBar2Title]			Text (30), 
	[RerouteBar2PrinterName]			Text (254), 
	[RerouteBar2PrinterType]			Long Integer, 
	[RerouteBar3Title]			Text (30), 
	[RerouteBar3PrinterName]			Text (254), 
	[RerouteBar3PrinterType]			Long Integer, 
	[RerouteBar4Title]			Text (30), 
	[RerouteBar4PrinterName]			Text (254), 
	[RerouteBar4PrinterType]			Long Integer, 
	[RerouteBar5Title]			Text (30), 
	[RerouteBar5PrinterName]			Text (254), 
	[RerouteBar5PrinterType]			Long Integer, 
	[RerouteBar6Title]			Text (30), 
	[RerouteBar6PrinterName]			Text (254), 
	[RerouteBar6PrinterType]			Long Integer, 
	[ExtendedSettings]			Memo/Hyperlink (255), 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [Streets]
 (
	[StreetID]			Long Integer NOT NULL, 
	[StreetName]			Text (23) NOT NULL, 
	[AddrFrom]			Text (6), 
	[AddrTo]			Text (6), 
	[MapCode]			Text (5), 
	[DeliveryCharge]			Single, 
	[DeliveryComp]			Single, 
	[NoDelivery]			Boolean NOT NULL, 
	[ZipCode]			Text (10) NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [Surcharges]
 (
	[SurchargeID]			Long Integer, 
	[SurchargeText]			Text (20) NOT NULL, 
	[SurchargeDescription]			Text (254), 
	[SurchargeInActive]			Boolean NOT NULL, 
	[SurchargeAmount]			Single NOT NULL, 
	[SurchargeBasis]			Text (1) NOT NULL, 
	[SurchargeWaiverMinTicket]			Single, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[SurchargeSecurityLevel]			Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [ZipCodes]
 (
	[ZipCode]			Text (10) NOT NULL, 
	[City]			Text (30) NOT NULL, 
	[State]			Text (30) NOT NULL, 
	[DeliveryCharge]			Single, 
	[DeliveryComp]			Single, 
	[AutoID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [ZReports]
 (
	[ZReportID]			Long Integer NOT NULL, 
	[ClosingDate]			DateTime NOT NULL, 
	[CumulativeTotal]			Double NOT NULL, 
	[ZReportTotal]			Double NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [BadCheckReasons]
 (
	[BadCheckReasonID]			Long Integer, 
	[BadCheckReasonText]			Text (20) NOT NULL, 
	[BadCheckReasonInActive]			Boolean NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [CustomerCreditAccounts]
 (
	[CustomerID]			Long Integer NOT NULL, 
	[FirstName]			Text (15) NOT NULL, 
	[LastName]			Text (15) NOT NULL, 
	[MailingAddress]			Text (30), 
	[MailingZipCode]			Text (10), 
	[SocialSecurityNumber]			Text (20), 
	[DriverLicenseNumber]			Text (20), 
	[DriverLicenseExpireDate]			DateTime, 
	[TotalCreditLimit]			Single NOT NULL, 
	[CreditAccountExpireDate]			DateTime, 
	[ScanCode]			Text (254), 
	[CreditAccountStatus]			Text (1) NOT NULL, 
	[CreditAccountNotes]			Text (254), 
	[AutoID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [DineInTableGroups]
 (
	[TableGroupID]			Long Integer, 
	[TableGroupText]			Text (20) NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [EmployeeTimeCards]
 (
	[TimeCardID]			Long Integer, 
	[EmployeeID]			Long Integer NOT NULL, 
	[WorkDate]			DateTime NOT NULL, 
	[ClockInTime]			DateTime NOT NULL, 
	[ClockOutTime]			DateTime, 
	[TipsReceived]			Single, 
	[PayrollID]			Long Integer, 
	[BankStartAmount]			Single, 
	[BankEndAmount]			Single, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[Break1BeginTime]			DateTime, 
	[Break1EndTime]			DateTime, 
	[Break1NCMinutes]			Long Integer, 
	[Break2BeginTime]			DateTime, 
	[Break2EndTime]			DateTime, 
	[Break2NCMinutes]			Long Integer, 
	[Break3BeginTime]			DateTime, 
	[Break3EndTime]			DateTime, 
	[Break3NCMinutes]			Long Integer, 
	[Break4BeginTime]			DateTime, 
	[Break4EndTime]			DateTime, 
	[Break4NCMinutes]			Long Integer, 
	[Break5BeginTime]			DateTime, 
	[Break5EndTime]			DateTime, 
	[Break5NCMinutes]			Long Integer, 
	[TotalRegularMinutes]			Long Integer, 
	[TotalDailyOverTimeMinutes]			Long Integer, 
	[TotalWeeklyOverTimeMinutes]			Long Integer, 
	[TotalDoubleTimeMinutes]			Long Integer, 
	[TotalWorkMinutes]			Long Integer, 
	[OrigClockInTime]			DateTime, 
	[OrigClockOutTime]			DateTime, 
	[OrigBreak1BeginTime]			DateTime, 
	[OrigBreak1EndTime]			DateTime, 
	[OrigBreak2BeginTime]			DateTime, 
	[OrigBreak2EndTime]			DateTime, 
	[OrigBreak3BeginTime]			DateTime, 
	[OrigBreak3EndTime]			DateTime, 
	[OrigBreak4BeginTime]			DateTime, 
	[OrigBreak4EndTime]			DateTime, 
	[OrigBreak5BeginTime]			DateTime, 
	[OrigBreak5EndTime]			DateTime, 
	[SpecialTimeType]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [FoodStampUsage]
 (
	[PaymentDateTime]			DateTime NOT NULL, 
	[CashierID]			Long Integer NOT NULL, 
	[NonCashierEmployeeID]			Long Integer, 
	[OrderID]			Long Integer NOT NULL, 
	[AmountPaid]			Single NOT NULL, 
	[AmountTendered]			Single NOT NULL, 
	[AutoID]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [InventoryItems]
 (
	[InventoryItemID]			Long Integer, 
	[InventoryItemText]			Text (30) NOT NULL, 
	[InventoryItemUnitName]			Text (30) NOT NULL, 
	[InventoryItemDescription]			Text (254), 
	[InventoryItemGroupID]			Long Integer NOT NULL, 
	[InventoryItemLocationID]			Long Integer NOT NULL, 
	[ItemDisplaySeqNumber]			Long Integer NOT NULL, 
	[InventoryItemInActive]			Boolean NOT NULL, 
	[InventoryItemReOrderPoint]			Single NOT NULL, 
	[CurrentQtyOnHand]			Single NOT NULL, 
	[CurrentValueOnHand]			Single NOT NULL, 
	[CurrentUnitCost]			Single NOT NULL, 
	[LastUpdateDateTime]			DateTime, 
	[InventoryItemSecLang]			Text (30), 
	[InventoryVendorID]			Long Integer NOT NULL, 
	[ReOrderLevel]			Single NOT NULL, 
	[MenuIngredientUnitsPerBaseQty]			Single NOT NULL, 
	[PackSizeBarcode]			Text (20), 
	[EachItemBarcode]			Text (20), 
	[TotalItemsPerPackSize]			Long Integer, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [MenuCategories]
 (
	[MenuCategoryID]			Long Integer, 
	[MenuCategoryText]			Text (15) NOT NULL, 
	[MenuCategoryInActive]			Boolean NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [MenuModifierPopUps]
 (
	[ModifierPopUpID]			Long Integer, 
	[MenuItemID]			Long Integer NOT NULL, 
	[MenuModifierID]			Long Integer NOT NULL, 
	[PopUpSequenceOrder]			Long Integer NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [OrderCheckDriverLicenseLogs]
 (
	[OrderID]			Long Integer NOT NULL, 
	[DriverLicenseNumber]			Text (20), 
	[ABANumber]			Text (5), 
	[AutoID]			Long Integer, 
	[CheckingAcctNumber]			Text (20) NOT NULL, 
	[EditTimestamp]			DateTime, 
	[EmployeeID]			Long Integer NOT NULL, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);

CREATE TABLE [POSClients]
 (
	[ComputerName]			Text (20) NOT NULL, 
	[License]			Text (26), 
	[CCode]			Text (4), 
	[LoginDateTime]			DateTime, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer
);

CREATE TABLE [SecuritySettings]
 (
	[SecuritySettingID]			Long Integer, 
	[SecuritySettingText]			Text (30) NOT NULL, 
	[MinSecLevel]			Text (1), 
	[OverrideSecLevel]			Text (1), 
	[SecurityEnforced]			Boolean NOT NULL, 
	[EditTimestamp]			DateTime, 
	[RemoteSiteNumber]			Integer, 
	[RemoteOrigRowID]			Long Integer, 
	[GlobalID]			Text (30), 
	[RowVer]			Text (30), 
	[SynchVer]			DateTime, 
	[StoreNumber]			Long Integer, 
	[HQRowID]			Text (50), 
	[LastRowHash]			Text (50), 
	[RowOwner]			Integer, 
	[RowGUID]			Text (50) NOT NULL
);


